import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CardProvider from "@/context/CardProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Food Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* project code  */}
        <header className="px-5 py-2 flex items-center justify-between gap-5 bg-stone-800">
          <Link href="/">
            <img src="./mainlogo.png" className="w-[120px] h-[60px] rounded-full" alt="" />
          </Link>

          <div className="space-x-5">
            <Link className="btn" href="/foods">
              Food
            </Link>
            <Link className="btn" href="/reviews">
              Reviews
            </Link>
          </div>
        </header>

        {/* eta main route and children ta holo component er */}
        <main className="px-5 py-8">
          {/* I am giving all the power cartProvided. Now the cardProvider is king */}
          <CardProvider>{children}</CardProvider>
        </main>
      </body>
    </html>
  );
}
